pipeline {
    agent any

    triggers {
        pollSCM('* * * * *')
    }

    environment {
        DIR_APPS = 'apps'
        DIR_K8S = 'k8s'
        MY_REGISTRY = 'worawut2547'
        DOCKER_IMAGE = 'myapp:latest'
        KUBE_NAMESPACE = 'my-apps'
        KUBE_DEPLOYMENT = 'myapp-deployment'
        KUBE_SERVICE = 'myapp-svc'
        KUBE_INGRESS = 'myapp-ingress'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                dir("${DIR_APPS}") {
                    script {
                        sh "docker build -t ${DOCKER_IMAGE} ."
                    }
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                dir("${DIR_APPS}") {
                    script {
                        sh "docker tag ${DOCKER_IMAGE} ${MY_REGISTRY}/myapp:latest"
                        sh "docker push ${MY_REGISTRY}/myapp:latest"
                    }
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                dir("${DIR_K8S}") {
                    script {
                        sh "kubectl apply -R -f ../k8s/myapp/"
                        sh "kubectl set image deployment/${KUBE_DEPLOYMENT} myapp-container=${MY_REGISTRY}/myapp:latest -n ${KUBE_NAMESPACE}"
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'This will always run, regardless of the build result.'
        }
        success {
            echo '✅ SUCCESS: The pipeline completed successfully.'
        }
        failure {
            echo '❌ FAILURE: The pipeline failed. Please check the logs for details.'
        }
    }
}